[metadata]
id = "nouvelle-gui"
name = "Nouvelle GUI"
description = "Graphical interface for the Nouvelle mod manager"

[runtime]
runs_on = "luajit"
entry_point = "gui.lua"

[permissions]
nouvelle = true
filesystem = { scope = ["./Mods"] }
internet = { scope = ["http:localhost"] }
