[metadata]
id = "nouvelle-gui"
name = "Nouvelle GUI"
author = "Nouvelle"
description = "Graphical interface for the Nouvelle mod manager"
update = false

[runtime]
runs_on = "luajit"
entry_point = "main"

[permissions]
nouvelle = true
filesystem = { scope = ["./Mods"] }
internet = { scope = ["http:localhost"] }
